# Generated by Django 5.0.4 on 2024-06-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingaddress_order_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('product', 'order')},
        ),
    ]
